spring.application.name=fonamif-backend

# Database Configuration - Default is H2 (Local)
spring.datasource.url=jdbc:h2:file:./data/fonamif_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Server
server.port=8080

# JWT Secret
jwt.secret=${BEZCODER_APP_JWTSECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
jwt.expiration=86400000

# Jackson - avoid infinite recursion with JPA relations
spring.jackson.serialization.fail-on-empty-beans=false
